"""add text analysis table

Revision ID: ae98f84831bf
Revises: 76f079a8d1ca
Create Date: 2026-03-02 20:51:49.385388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae98f84831bf'
down_revision: Union[str, Sequence[str], None] = '76f079a8d1ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=30), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('toxicity_score', sa.Float(), nullable=True),
    sa.Column('toxicity_label', sa.String(length=50), nullable=True),
    sa.Column('emotions', sa.JSON(), nullable=True),
    sa.Column('primary_emotion', sa.String(length=50), nullable=True),
    sa.Column('tone', sa.String(length=30), nullable=True),
    sa.Column('toxicity_model', sa.String(length=120), nullable=True),
    sa.Column('emotion_model', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_analyses_created_at'), 'text_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_text_analyses_object_id'), 'text_analyses', ['object_id'], unique=False)
    op.create_index(op.f('ix_text_analyses_object_type'), 'text_analyses', ['object_type'], unique=False)
    op.create_index(op.f('ix_text_analyses_user_id'), 'text_analyses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_text_analyses_user_id'), table_name='text_analyses')
    op.drop_index(op.f('ix_text_analyses_object_type'), table_name='text_analyses')
    op.drop_index(op.f('ix_text_analyses_object_id'), table_name='text_analyses')
    op.drop_index(op.f('ix_text_analyses_created_at'), table_name='text_analyses')
    op.drop_table('text_analyses')
    # ### end Alembic commands ###
