"""add reactions table

Revision ID: d86eed2b88eb
Revises: e98d7f00562f
Create Date: 2026-03-11 10:37:14.452422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd86eed2b88eb'
down_revision: Union[str, Sequence[str], None] = 'e98d7f00562f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=20), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('reaction_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'object_type', 'object_id', name='uq_user_reaction_per_object')
    )
    op.create_index(op.f('ix_reactions_object_id'), 'reactions', ['object_id'], unique=False)
    op.create_index(op.f('ix_reactions_object_type'), 'reactions', ['object_type'], unique=False)
    op.create_index(op.f('ix_reactions_user_id'), 'reactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reactions_user_id'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_object_type'), table_name='reactions')
    op.drop_index(op.f('ix_reactions_object_id'), table_name='reactions')
    op.drop_table('reactions')
    # ### end Alembic commands ###
