"""add mentorship system tables

Revision ID: e08cd92ef110
Revises: 304c123f8684
Create Date: 2026-03-06 02:14:36.614863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08cd92ef110'
down_revision: Union[str, Sequence[str], None] = '304c123f8684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mentor_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_user_id', sa.Integer(), nullable=False),
    sa.Column('mentee_user_id', sa.Integer(), nullable=False),
    sa.Column('object_type', sa.String(length=30), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mentor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mentor_notes_created_at'), 'mentor_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_mentor_notes_mentee_user_id'), 'mentor_notes', ['mentee_user_id'], unique=False)
    op.create_index(op.f('ix_mentor_notes_mentor_user_id'), 'mentor_notes', ['mentor_user_id'], unique=False)
    op.create_index(op.f('ix_mentor_notes_object_id'), 'mentor_notes', ['object_id'], unique=False)
    op.create_index(op.f('ix_mentor_notes_object_type'), 'mentor_notes', ['object_type'], unique=False)
    op.create_table('mentorships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mentor_user_id', sa.Integer(), nullable=False),
    sa.Column('mentee_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['mentee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['mentor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mentor_user_id', 'mentee_user_id', name='uq_mentor_mentee')
    )
    op.create_index(op.f('ix_mentorships_created_at'), 'mentorships', ['created_at'], unique=False)
    op.create_index(op.f('ix_mentorships_mentee_user_id'), 'mentorships', ['mentee_user_id'], unique=False)
    op.create_index(op.f('ix_mentorships_mentor_user_id'), 'mentorships', ['mentor_user_id'], unique=False)
    op.create_index(op.f('ix_mentorships_status'), 'mentorships', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mentorships_status'), table_name='mentorships')
    op.drop_index(op.f('ix_mentorships_mentor_user_id'), table_name='mentorships')
    op.drop_index(op.f('ix_mentorships_mentee_user_id'), table_name='mentorships')
    op.drop_index(op.f('ix_mentorships_created_at'), table_name='mentorships')
    op.drop_table('mentorships')
    op.drop_index(op.f('ix_mentor_notes_object_type'), table_name='mentor_notes')
    op.drop_index(op.f('ix_mentor_notes_object_id'), table_name='mentor_notes')
    op.drop_index(op.f('ix_mentor_notes_mentor_user_id'), table_name='mentor_notes')
    op.drop_index(op.f('ix_mentor_notes_mentee_user_id'), table_name='mentor_notes')
    op.drop_index(op.f('ix_mentor_notes_created_at'), table_name='mentor_notes')
    op.drop_table('mentor_notes')
    # ### end Alembic commands ###
