"""add post media fields

Revision ID: ee82c9feacdd
Revises: 7f33f34d16e2
Create Date: 2026-03-10 17:15:43.573143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee82c9feacdd'
down_revision: Union[str, Sequence[str], None] = '7f33f34d16e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('media_url', sa.String(length=500), nullable=True))
    op.add_column('posts', sa.Column('media_type', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'media_type')
    op.drop_column('posts', 'media_url')
    # ### end Alembic commands ###
